
name: Tests and Coverage
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - name: Install coverage
        run: pip3 install coverage[toml]
      - name: Install requirements
        run: pip3 install -r requirements.txt
      - name: Run the tests
        run: coverage run --source=wolk/ -m unittest
      - name: Report coverage
        run: coverage report --skip-empty
